# Generated by Django 5.1.5 on 2025-02-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_order_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('dt',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказ'},
        ),
    ]
