# Generated by Django 5.1.5 on 2025-02-23 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='building',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='structure',
        ),
    ]
